#!/bin/sh

#set -e

LOGFILE=/var/log/complaints.queue/complaints_queue.log
INIFILE=/etc/complaints.queue/complaints_queue.ini
PIDFILE=`grep pidfile $INIFILE | cut -d= -f2`

# don't restart if last log records are fresh
tail $LOGFILE | grep -q `date +%Y-%m-%d` && exit 0

# don't restart if no pidfile present
test -s $PIDFILE || exit 0
PID=`cat $PIDFILE`

# don't restart if not started
ps ax | grep -q -P "$PID .{10,90}complaints_queue" || exit 0

# now kill, angel will restart it
echo `date +"%Y-%m-%d %H:%M:%S"` Restart by cron >>$LOGFILE
kill $PID
